blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/johanviberg/proxycheck-sdk/discussions
    about: Please ask and answer questions here
  - name: ProxyCheck.io Support
    url: https://proxycheck.io/contact
    about: For issues with the ProxyCheck.io API itself